Fixed undefined method `[]' for nil:NilClass (NoMethodError)
The last commit introduced this problem because it was using a class member variable that didn't exist